// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxSessions   uint32                 `protobuf:"varint,4,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentRegistration) GetMaxSessions() uint32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *AgentRegistration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AgentDescriptor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Capabilities      []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxSessions       uint32                 `protobuf:"varint,4,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	ActiveSessions    uint32                 `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	AvailableSessions uint32                 `protobuf:"varint,6,opt,name=available_sessions,json=availableSessions,proto3" json:"available_sessions,omitempty"`
	Available         bool                   `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"`
	Enabled           bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAtUnix     int64                  `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentDescriptor) Reset() {
	*x = AgentDescriptor{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptor) ProtoMessage() {}

func (x *AgentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptor.ProtoReflect.Descriptor instead.
func (*AgentDescriptor) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDescriptor) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentDescriptor) GetMaxSessions() uint32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *AgentDescriptor) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *AgentDescriptor) GetAvailableSessions() uint32 {
	if x != nil {
		return x.AvailableSessions
	}
	return 0
}

func (x *AgentDescriptor) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *AgentDescriptor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentDescriptor) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentRegistration     `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentRequest) GetAgent() *AgentRegistration {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescriptor       `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentResponse) GetAgent() *AgentDescriptor {
	if x != nil {
		return x.Agent
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentDescriptor       `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAgent() *AgentDescriptor {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyAvailable bool                   `protobuf:"varint,1,opt,name=only_available,json=onlyAvailable,proto3" json:"only_available,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsRequest) GetOnlyAvailable() bool {
	if x != nil {
		return x.OnlyAvailable
	}
	return false
}

func (x *ListAgentsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentDescriptor     `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*AgentDescriptor {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AssignSessionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VisitorId           string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	VisitorName         string                 `protobuf:"bytes,2,opt,name=visitor_name,json=visitorName,proto3" json:"visitor_name,omitempty"`
	PreferredCapability string                 `protobuf:"bytes,3,opt,name=preferred_capability,json=preferredCapability,proto3" json:"preferred_capability,omitempty"`
	Source              string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AssignSessionRequest) Reset() {
	*x = AssignSessionRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSessionRequest) ProtoMessage() {}

func (x *AssignSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSessionRequest.ProtoReflect.Descriptor instead.
func (*AssignSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AssignSessionRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *AssignSessionRequest) GetVisitorName() string {
	if x != nil {
		return x.VisitorName
	}
	return ""
}

func (x *AssignSessionRequest) GetPreferredCapability() string {
	if x != nil {
		return x.PreferredCapability
	}
	return ""
}

func (x *AssignSessionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AssignSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assigned      bool                   `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSessionResponse) Reset() {
	*x = AssignSessionResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSessionResponse) ProtoMessage() {}

func (x *AssignSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSessionResponse.ProtoReflect.Descriptor instead.
func (*AssignSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AssignSessionResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *AssignSessionResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AssignSessionResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AssignSessionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseSessionRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseSessionResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x16goflylivechat.agent.v1\"\xb2\x01\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12!\n" +
	"\fmax_sessions\x18\x04 \x01(\rR\vmaxSessions\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"\xce\x02\n" +
	"\x0fAgentDescriptor\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12!\n" +
	"\fmax_sessions\x18\x04 \x01(\rR\vmaxSessions\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\rR\x0eactiveSessions\x12-\n" +
	"\x12available_sessions\x18\x06 \x01(\rR\x11availableSessions\x12\x1c\n" +
	"\tavailable\x18\a \x01(\bR\tavailable\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnix\"W\n" +
	"\x14RegisterAgentRequest\x12?\n" +
	"\x05agent\x18\x01 \x01(\v2).goflylivechat.agent.v1.AgentRegistrationR\x05agent\"V\n" +
	"\x15RegisterAgentResponse\x12=\n" +
	"\x05agent\x18\x01 \x01(\v2'.goflylivechat.agent.v1.AgentDescriptorR\x05agent\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"R\n" +
	"\x11HeartbeatResponse\x12=\n" +
	"\x05agent\x18\x01 \x01(\v2'.goflylivechat.agent.v1.AgentDescriptorR\x05agent\"Z\n" +
	"\x11ListAgentsRequest\x12%\n" +
	"\x0eonly_available\x18\x01 \x01(\bR\ronlyAvailable\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\"U\n" +
	"\x12ListAgentsResponse\x12?\n" +
	"\x06agents\x18\x01 \x03(\v2'.goflylivechat.agent.v1.AgentDescriptorR\x06agents\"\xa3\x01\n" +
	"\x14AssignSessionRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\x12!\n" +
	"\fvisitor_name\x18\x02 \x01(\tR\vvisitorName\x121\n" +
	"\x14preferred_capability\x18\x03 \x01(\tR\x13preferredCapability\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x89\x01\n" +
	"\x15AssignSessionResponse\x12\x1a\n" +
	"\bassigned\x18\x01 \x01(\bR\bassigned\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"6\n" +
	"\x15ReleaseSessionRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\"4\n" +
	"\x16ReleaseSessionResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased2\xa2\x04\n" +
	"\fAgentService\x12l\n" +
	"\rRegisterAgent\x12,.goflylivechat.agent.v1.RegisterAgentRequest\x1a-.goflylivechat.agent.v1.RegisterAgentResponse\x12`\n" +
	"\tHeartbeat\x12(.goflylivechat.agent.v1.HeartbeatRequest\x1a).goflylivechat.agent.v1.HeartbeatResponse\x12c\n" +
	"\n" +
	"ListAgents\x12).goflylivechat.agent.v1.ListAgentsRequest\x1a*.goflylivechat.agent.v1.ListAgentsResponse\x12l\n" +
	"\rAssignSession\x12,.goflylivechat.agent.v1.AssignSessionRequest\x1a-.goflylivechat.agent.v1.AssignSessionResponse\x12o\n" +
	"\x0eReleaseSession\x12-.goflylivechat.agent.v1.ReleaseSessionRequest\x1a..goflylivechat.agent.v1.ReleaseSessionResponseB\x1fZ\x1dgoflylivechat/agentpb;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(*AgentRegistration)(nil),      // 0: goflylivechat.agent.v1.AgentRegistration
	(*AgentDescriptor)(nil),        // 1: goflylivechat.agent.v1.AgentDescriptor
	(*RegisterAgentRequest)(nil),   // 2: goflylivechat.agent.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),  // 3: goflylivechat.agent.v1.RegisterAgentResponse
	(*HeartbeatRequest)(nil),       // 4: goflylivechat.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 5: goflylivechat.agent.v1.HeartbeatResponse
	(*ListAgentsRequest)(nil),      // 6: goflylivechat.agent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),     // 7: goflylivechat.agent.v1.ListAgentsResponse
	(*AssignSessionRequest)(nil),   // 8: goflylivechat.agent.v1.AssignSessionRequest
	(*AssignSessionResponse)(nil),  // 9: goflylivechat.agent.v1.AssignSessionResponse
	(*ReleaseSessionRequest)(nil),  // 10: goflylivechat.agent.v1.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil), // 11: goflylivechat.agent.v1.ReleaseSessionResponse
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: goflylivechat.agent.v1.RegisterAgentRequest.agent:type_name -> goflylivechat.agent.v1.AgentRegistration
	1,  // 1: goflylivechat.agent.v1.RegisterAgentResponse.agent:type_name -> goflylivechat.agent.v1.AgentDescriptor
	1,  // 2: goflylivechat.agent.v1.HeartbeatResponse.agent:type_name -> goflylivechat.agent.v1.AgentDescriptor
	1,  // 3: goflylivechat.agent.v1.ListAgentsResponse.agents:type_name -> goflylivechat.agent.v1.AgentDescriptor
	2,  // 4: goflylivechat.agent.v1.AgentService.RegisterAgent:input_type -> goflylivechat.agent.v1.RegisterAgentRequest
	4,  // 5: goflylivechat.agent.v1.AgentService.Heartbeat:input_type -> goflylivechat.agent.v1.HeartbeatRequest
	6,  // 6: goflylivechat.agent.v1.AgentService.ListAgents:input_type -> goflylivechat.agent.v1.ListAgentsRequest
	8,  // 7: goflylivechat.agent.v1.AgentService.AssignSession:input_type -> goflylivechat.agent.v1.AssignSessionRequest
	10, // 8: goflylivechat.agent.v1.AgentService.ReleaseSession:input_type -> goflylivechat.agent.v1.ReleaseSessionRequest
	3,  // 9: goflylivechat.agent.v1.AgentService.RegisterAgent:output_type -> goflylivechat.agent.v1.RegisterAgentResponse
	5,  // 10: goflylivechat.agent.v1.AgentService.Heartbeat:output_type -> goflylivechat.agent.v1.HeartbeatResponse
	7,  // 11: goflylivechat.agent.v1.AgentService.ListAgents:output_type -> goflylivechat.agent.v1.ListAgentsResponse
	9,  // 12: goflylivechat.agent.v1.AgentService.AssignSession:output_type -> goflylivechat.agent.v1.AssignSessionResponse
	11, // 13: goflylivechat.agent.v1.AgentService.ReleaseSession:output_type -> goflylivechat.agent.v1.ReleaseSessionResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
